### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by JanSifrer** [JanSifrer/APPR-2018-19#1]
Pozdravljeni,
pri uvozu zemljevida se mi pojavlja neka napaka, in sicer program pravi: Cannot open data source. Kako bi lahko najlažje popravil to napako?

Hvala in lep pozdrav.

**Comment by jaanos** [comment]
Treba bo popraviti `uvozi.zemljevid.r` - poglej JernejcicZan/APPR-2018-19#1.

**Comment by JanSifrer** [comment]
Najlepša Vam hvala. Sedaj deluje.
