### ISSUE TITLE
Povezava za Binder in grafi

### ISSUE THREAD

**Issue by jaanos** [JanSifrer/APPR-2018-19#2]
Poročilo ti prevede, tako da bom dodal povezavo na repozitorij za zagovore. Če boš do predstavitve še kaj spreminjal, mi prosim javi, da jo posodobim.

Opažam sicer, da poročilo nastaja v datoteki `test.Rmd`, tako da bo potrebno popraviti povezavo za Binder:

https://github.com/JanSifrer/APPR-2018-19/blob/5986ef7a344c27215a7b9da55a2853462f969293/README.md#L7

bo treba popraviti v
```markdown
* [![Shiny](http://mybinder.org/badge.svg)](http://beta.mybinder.org/v2/gh/JanSifrer/APPR-2018-19/master?urlpath=shiny/APPR-2018-19/projekt.Rmd) Shiny
```
Lahko pa seveda svoje poročilo premakneš v `projekt.Rmd` - potem povezave ne bo treba popravljati.

Na grafih, kjer prikazuješ stolpce za vsako starostno skupino, te niso v pravem vrstnem redu (R jih namreč razporedi leksikografsko). Da zagotoviš ustrezno ureditev, bo treba narediti urejeni faktor - najbolje, da za to poskrbiš kar pri uvozu. Najlažje bo, če najprej definiraš vektor s kategorijami v pravem vrstnem redu:
```R
starosti <- c("0-4 let", "5-9 let", "10-14 let", "15-19 let", "20-24 let", "25-29 let",
              "30-34 let", "35-39 let", "40-44 let", "45-49 let", "50-54 let", "55-59 let",
              "60-64 let", "65-69 let", "70-74 let", "75-79 let", "80-84 let", "85 + let")
```
Potem lahko popraviš stolpec `starost` tako, da pri `mutate` dodaš parameter `starost=parse_factor(starost, starosti, ordered=TRUE)`. Če imaš v podatkih sumarne podatke (skupno število, povprečna starost), jih odstrani iz razpredelnice.

Pri zemljevidu lahko vidiš, da Ljubljana močno izstopa - smiselno bi bilo dobljeno številko deliti s prebivalstvom občine, pa bi se morda kaj več dalo videti iz zemljevida.

**Comment by JanSifrer** [comment]
Pozdravljeni,
Najlepša Vam hvala za predloge!
Sem jih upošteval in projekt premaknil v `projekt.Rmd`, tako da bi Binder sedaj moral delovati. 
Pri zemljevidu pa imam še eno vprašanje - ali se da na kakšen enostaven način spremeniti legendo? Pač da bi se recimo barva menjavala na 0.1, torej od 0.0 pa do 0.1 en odtenek, od 0.1 pa do 0.2 drug, itd.?

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.

Če prav razumem, bi rad naredil diskretno skalo z eno barvo za vsak interval. To lahko dosežeš tako, da vrednosti zaokrožiš in pretvoriš v faktorje, npr.
```R
ggplot() + geom_polygon(data=left_join(zemljevid, razlika.obcine,
                                       by=c("OB_UIME"="obcina")),
                        aes(x=long, y=lat, group=group,
                            fill=factor(round(razlika+0.05, 1)))) +
  ggtitle("Razlika priseljenih in odseljenih deljena s številom prebivalcev") +
  xlab("") + ylab("") +
  scale_fill_discrete(guide=guide_legend(title="Število"),
                      labels=. %>% { paste({parse_number(.) %>% { . - 0.1 }}, "-", .) })
```
Parameter `labels` pri `scale_fill_discrete` sprejme funkcijo, ki iz vrednosti naredi oznako v legendi - lahko bi sicer tudi podal vektor z želenimi oznakami.

**Comment by JanSifrer** [comment]
Tako ja, to sem želel narediti. 
Najlepša Vam hvala za odgovor.
