### ISSUE TITLE
Razrezan zemljevid Slovenije

### ISSUE THREAD

**Issue by JanSifrer** [JanSifrer/APPR-2018-19#3]
Pozdravljeni,
Imam dve vprašanji, in sicer:

vprašanje: koda ki mi razreže Slovenijo na n-delov (koda je v mapi analiza.r), se mi zdi da ne deluje pravilo, pač Ljubljano da zmeraj v svojo skupino, in to se mi zdi da ne deluje tako kot sem si zamislil (hotel sem jih dati v skupine glede na stolpec "razlika" v tabeli "razlika.obcine", da jih pa nekako drugače, ne vem kako, samo vem da narobe.
vprašanje: Pri shiny-ju sem v server.R napisal funkcijo iz 1. vprašanja, in me zanima, zakaj mi aplikacija če jo zaženem javi napako: Error: could not find function "left_join", ter mi ne pokaže zemljevida? Zemljevid pa, če spregledam napako, ki je nekje v definiciji funkcije zemljevid.slovenije(), v poročilu deluje brez težav?

Lepo pozdravljeni,
Jan

**Comment by jaanos** [comment]
Delitev na skupine opravljaš po treh podatkih: absolutnem številu priseljenih, absolutnem številu odseljenih in razliki, deljeni s prebivalstvom. Ker sta prva dva podatka pri Ljubljani veliko večja kot drugod, bo Ljubljana razporejena v svojo skupino. Svetujem, da raje števila priseljenih in odseljenih deliš s številom prebivalcev - razlike potem niti ne potrebuješ, saj ne bi smela vplivati na razporeditev.

Shiny aplikacija ti bo delovala, če imaš pred tem uvožene ustrezne knjižnice in poračunane potrebne podatke. Pri prevajanju poročila bo to res, saj tam že pokličeš vse ustrezne programe, če jo pa poganjaš na roko (s klikom na *Run App*) pa poskrbi, da si pred tem pognal vse programe (poženi torej vse ukaze `source` v poročilu - lahko pa tudi pod *Run* izbereš *Run All*, da se požene vsa koda v poročilu).

**Comment by JanSifrer** [comment]
Hvala, zadeva sedaj deluje :)
