### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by JanSifrer** [JanSifrer/APPR-2018-19#4]
Pozdravljeni,
ponovno sem prišel do neke 'čudne' napake. Pri `Shinyu` čisto na koncu poročila nekaj ne dela, in sicer se pojavlja napaka: `Error:  subscript out of bounds`. Napaka izgine če v datoteki `ui.R` v 11 vrstici napišem `c("Kranj", "Bled"), vendar pa se potem tukaj pojavi nova napaka in sicer: graf se noče narisati v poročilu, če pa zaženem samo aplikacijo se pa graf prikaže tako kot če bi ga zagnal v konzoli - tam v Viewer-ju (desni spodnji okvirček).. 
Obstaja mogoče kakšna elegantna rešitev tega problema? :D 

Za pomoč, se Vam že v naprej najlepše zahvaljujem!

Jan

**Comment by jaanos** [comment]
Za seznam možnosti pri `selectInput` trenutno podajaš celoten stolpec, s ponovljenimi občinami, zato pride do napake. Zadostovalo bo seveda, da je vsaka občina podana samo enkrat, npr. s `sort(unique(selitveno.gibanje$obcina))`, da bodo te še urejene.

Kar se pa tiče prikazovanja interaktivnega grafa s knjižnico `dygraph`, bo potrebno namesto `renderPlot` in `plotOutput` uporabiti `renderDygraph` in `dygraphOutput` - glej tudi [primer](https://rstudio.github.io/dygraphs/shiny.html).

**Comment by JanSifrer** [comment]
Najlepša Vam hvala. Sedaj deluje.
Vas lahko samo še vprašam, ali bi bilo mogoče smiselno še dodati nov zavihek pri `Shinyu` kjer bi se podobno, kot za priseljene po občinah, dalo pogledat še za odseljene, torej da bi delal nov graf? 
Ali bi bilo morda boljše, če naredim samo nov `selectIput` v katerem se da izbrati med njima, pa mogoče dodam še možnost za selitveni prirast po občinah?

**Comment by jaanos** [comment]
Če graf rišeš na isti način (torej npr. samo spremeniš uporabljeni filter), potem je smiselno, da dodaš izbirnik, kjer se izbere, kaj bo graf prikazoval. Če bi pa hotel prikazati drugačen graf, pa bi seveda bilo smiselno narediti nov zavihek.

**Comment by JanSifrer** [comment]
Aha okey, sem dodal izbirnika, tako pri grafu, kot tudi pri zemljevidu.
